[build]
  command = "npm run build"
  publish = "dist"

[context.deploy-preview]
  command = "npm start"

[template.environment]
  TOXIC_PAGE_TITLE = "Hello Toxic | React Starter"
  TOXIC_COMPANY_LOGO = ""
  TOXIC_SUPPORT_CONTACT_LINK = "https://toxicdev.me/discord"
